[features]
seeds = false
skip-lint = false
[programs.devnet]
ahoy_there = "BChMVQqmD1jLdGcRkhqWx6ET2owUpAA9YvD5Z12c3QnC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/berkingurcan/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
